<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../install/paths.class.php';

/**
 * \file        class/install/vendorlayout.class.php
 * \ingroup     cyphtWebmail
 * \brief       Bridges Cypht's flat-Composer layout against its own scripts,
 *              which expect a nested vendor/. Also home to the recursive
 *              copy/delete helpers CyphtPipeline::publishSite() uses.
 */
class CyphtVendorLayout
{
	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtPaths
	 */
	private $paths;

	/**
	 * @param CyphtPaths $paths
	 */
	public function __construct(CyphtPaths $paths)
	{
		$this->paths = $paths;
	}

	/**
	 * Cypht's scripts expect a nested vendor/autoload.php in their own package
	 * directory; installed flat, there is none. Shims the path they expect.
	 * Re-created every build, since Composer re-extracts the package whenever
	 * its locked version changes.
	 *
	 * @return bool
	 */
	public function ensureCyphtVendorBridge()
	{
		$bridgeDir = $this->paths->getCyphtPath() . '/vendor';
		$bridgeFile = $bridgeDir . '/autoload.php';

		if (!is_dir($bridgeDir) && !mkdir($bridgeDir, 0755, true) && !is_dir($bridgeDir)) {
			$this->error = 'Could not create ' . $bridgeDir;
			return false;
		}

		$content = "<?php\n" .
			"// Auto-generated by CyphtVendorLayout::ensureCyphtVendorBridge(). Do not edit;\n" .
			"// recreated on every build. Forwards Cypht's own scripts to the module's\n" .
			"// shared vendor/ autoloader.\n" .
			"return require dirname(__DIR__, 3).'/autoload.php';\n";

		if (file_put_contents($bridgeFile, $content) === false) {
			$this->error = 'Could not write ' . $bridgeFile;
			return false;
		}

		return $this->mirrorVendorAssets($bridgeDir);
	}

	/**
	 * Everything Cypht reads from VENDOR_PATH off disk rather than through
	 * the autoloader.
	 *
	 * Globs, not whole packages: 6.5MB of 150MB. From config_gen.php 482, 556,
	 * 616, 618, lib/js_libs.php JS_LIBS and developer/modules.php:36. Regrep
	 * VENDOR_PATH and JS_LIBS after a Cypht upgrade.
	 *
	 * @return array<string,string[]> Composer vendor namespace => path globs
	 */
	private function assetManifest()
	{
		return array(
			'twbs' => array(
				'bootstrap/dist/css/bootstrap.min.css',
				// Cypht's own JS is inert without it: Bootstrap drives the
				// dropdowns and the modals Hm_Modal builds on.
				'bootstrap/dist/js/bootstrap.bundle.min.js',
				'bootstrap-icons/font/bootstrap-icons.css',
				'bootstrap-icons/font/fonts/*',
			),
			'thomaspark' => array(
				'bootswatch/dist/*/bootstrap.min.css',
			),
			// Read by the developer module, which falls back to shelling out
			// to git when it is missing.
			'composer' => array(
				'installed.json',
			),
		);
	}

	/**
	 * Put those assets where Cypht's scripts expect them.
	 *
	 * Copies, not links: a symlink needs privileges Windows withholds from
	 * Apache, a junction needs exec(), and neither survives being zipped.
	 * Failure is fatal here because the site just renders unstyled.
	 *
	 * @param string $bridgeDir vendor/ inside the Cypht package
	 * @return bool
	 */
	private function mirrorVendorAssets($bridgeDir)
	{
		$moduleVendor = $this->paths->getModuleRoot() . '/vendor';

		foreach ($this->assetManifest() as $vendor => $globs) {
			$source = $moduleVendor . '/' . $vendor;
			$dest = $bridgeDir . '/' . $vendor;
			$marker = $bridgeDir . '/.' . $vendor . '.bridged';

			if (!is_dir($source)) {
				continue;
			}

			$fingerprint = $this->bridgeFingerprint($vendor);
			if ($fingerprint !== '' && @file_get_contents($marker) === $fingerprint
				&& $this->assetsPresent($source, $dest, $globs)) {
				continue;
			}

			// Older builds left a symlink, a junction or a full copy here.
			if (!$this->resetDir($dest)) {
				return false;
			}

			$copied = 0;
			foreach ($globs as $glob) {
				foreach ((array) glob($source . '/' . $glob) as $file) {
					if (!is_file($file)) {
						continue;
					}
					$relative = substr($file, strlen($source) + 1);
					if ($this->copyFile($file, $dest . '/' . $relative)) {
						$copied++;
					}
				}
			}

			if (!$this->assetsPresent($source, $dest, $globs)) {
				$this->error = 'Could not mirror ' . $vendor . ' assets into ' . $dest .
					' (' . $copied . ' file(s) copied). Cypht builds its stylesheet from these, ' .
					'so the site would come out unstyled. Check permissions on ' . $bridgeDir . '.';
				return false;
			}

			@file_put_contents($marker, $fingerprint);
		}

		return true;
	}

	/**
	 * True when every file the globs match in the source has a counterpart in
	 * the destination. Also the post-copy check, so a partial copy is a
	 * failure rather than a half-styled build.
	 *
	 * @param string $source
	 * @param string $dest
	 * @param string[] $globs
	 * @return bool
	 */
	private function assetsPresent($source, $dest, array $globs)
	{
		foreach ($globs as $glob) {
			$matches = glob($source . '/' . $glob);
			if (!is_array($matches) || count($matches) === 0) {
				continue;
			}
			foreach ($matches as $file) {
				if (!is_file($file)) {
					continue;
				}
				if (!is_file($dest . '/' . substr($file, strlen($source) + 1))) {
					return false;
				}
			}
		}

		return true;
	}

	/**
	 * Copy one file, creating its parent directories.
	 *
	 * @param string $src
	 * @param string $dst
	 * @return bool
	 */
	private function copyFile($src, $dst)
	{
		$dir = dirname($dst);
		if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
			return false;
		}

		return @copy($src, $dst);
	}

	/**
	 * Hash of the installed versions under a vendor namespace, so the bridge
	 * is only rebuilt when composer actually moves one of them.
	 *
	 * @param string $vendor Composer vendor namespace
	 * @return string
	 */
	private function bridgeFingerprint($vendor)
	{
		$installedJson = $this->paths->getModuleRoot() . '/vendor/composer/installed.json';
		if (!file_exists($installedJson)) {
			return '';
		}

		$data = json_decode(file_get_contents($installedJson), true);
		if (!is_array($data)) {
			return '';
		}
		$packages = isset($data['packages']) ? $data['packages'] : $data;

		$parts = array();
		foreach ($packages as $pkg) {
			if (!empty($pkg['name']) && strpos($pkg['name'], $vendor . '/') === 0) {
				$parts[] = $pkg['name'] . '@' . (isset($pkg['version']) ? $pkg['version'] : '?');
			}
		}
		if (count($parts) === 0) {
			/* "composer" is a directory Composer writes, not a package it
			 * lists, so nothing matches the namespace. Hash the file instead
			 * of giving up, or that entry re-copies on every build. */
			return md5_file($installedJson);
		}
		sort($parts);

		return md5(implode(',', $parts));
	}

	/**
	 * Clear a real directory, symlink or Windows junction and hand back an
	 * empty directory.
	 *
	 * Removals run unconditionally, and success is whether mkdir() then works:
	 * a dangling junction is invisible to is_dir(), file_exists() and lstat()
	 * while still holding the name, so probing first is useless. Order matters,
	 * rmdir clears a junction without following it; deleteRecursive would walk
	 * one and delete the Bootstrap files it points at.
	 *
	 * @param string $dir
	 * @return bool
	 */
	private function resetDir($dir)
	{
		if (!@unlink($dir) && !@rmdir($dir) && is_dir($dir)) {
			$this->deleteRecursive($dir);
		}

		clearstatcache(true, $dir);

		if (!@mkdir($dir, 0755, true) && !is_dir($dir)) {
			$this->error = 'Could not clear ' . $dir . ', left behind by an earlier ' .
				'build. Delete it by hand and build again.';
			return false;
		}

		return true;
	}

	/**
	 * Recursively copy a directory (Cypht's site/ output isn't huge, this
	 * is only run when the button is clicked, not on every page load). Also
	 * used by CyphtPipeline::publishSite().
	 *
	 * @param string $src
	 * @param string $dst
	 * @return void
	 */
	public function copyRecursive($src, $dst)
	{
		if (!is_dir($dst)) {
			mkdir($dst, 0755, true);
		}
		$items = scandir($src);
		foreach ($items as $item) {
			if ($item === '.' || $item === '..') {
				continue;
			}
			$srcPath = $src . '/' . $item;
			$dstPath = $dst . '/' . $item;
			if (is_dir($srcPath)) {
				$this->copyRecursive($srcPath, $dstPath);
			} else {
				copy($srcPath, $dstPath);
			}
		}
	}

	/**
	 * Also used by CyphtPipeline::publishSite() to wipe the previous
	 * published copy before publishing a fresh one.
	 *
	 * @param string $dir
	 * @return void
	 */
	public function deleteRecursive($dir)
	{
		$items = scandir($dir);
		foreach ($items as $item) {
			if ($item === '.' || $item === '..') {
				continue;
			}
			$path = $dir . '/' . $item;
			if (is_dir($path)) {
				$this->deleteRecursive($path);
			} else {
				unlink($path);
			}
		}
		rmdir($dir);
	}
}
