<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../install/paths.class.php';

/**
 * \file        class/install/vendorlayout.class.php
 * \ingroup     cyphtwebmail
 * \brief       Bridges Cypht's flat-Composer-dependency layout (installed
 *              as a direct dependency of this module, same as Tiki does)
 *              against Cypht's own scripts, which expect a nested vendor/
 *              inside their own package directory. Also home to the
 *              generic recursive copy/delete helpers, also used by
 *              CyphtPipeline::publishSite().
 */
class CyphtVendorLayout
{
	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtPaths
	 */
	private $paths;

	/**
	 * @param CyphtPaths $paths
	 */
	public function __construct(CyphtPaths $paths)
	{
		$this->paths = $paths;
	}

	/**
	 * Cypht's own scripts expect a nested vendor/autoload.php inside their
	 * own package directory, since they're written for a standalone Cypht
	 * checkout. We install Cypht as a flat dependency instead (same as
	 * Tiki), so there is no nested vendor/ there. This creates a shim at
	 * the path Cypht expects, forwarding to the real shared autoloader.
	 * Must be re-created on every build: Composer re-extracts a package's
	 * directory whenever its locked version changes.
	 *
	 * @return bool
	 */
	public function ensureCyphtVendorBridge()
	{
		$bridgeDir = $this->paths->getCyphtPath() . '/vendor';
		$bridgeFile = $bridgeDir . '/autoload.php';

		if (!is_dir($bridgeDir) && !mkdir($bridgeDir, 0755, true) && !is_dir($bridgeDir)) {
			$this->error = 'Could not create ' . $bridgeDir;
			return false;
		}

		$content = "<?php\n" .
			"// Auto-generated by CyphtVendorLayout::ensureCyphtVendorBridge(). Do not edit;\n" .
			"// recreated on every build. Forwards Cypht's own scripts to the module's\n" .
			"// shared vendor/ autoloader.\n" .
			"return require dirname(__DIR__, 3).'/autoload.php';\n";

		if (file_put_contents($bridgeFile, $content) === false) {
			$this->error = 'Could not write ' . $bridgeFile;
			return false;
		}

		// Same flat-dependency problem as autoload.php above, but for the raw
		// asset directories (Bootstrap, Bootswatch) config_gen.php reads off
		// disk. Rebuilt only when the installed versions change: copying them
		// takes minutes and overruns the request.
		$moduleVendor = $this->paths->getModuleRoot() . '/vendor';
		foreach (array('twbs', 'thomaspark') as $vendor) {
			$target = $moduleVendor . '/' . $vendor;
			$link = $bridgeDir . '/' . $vendor;
			$marker = $bridgeDir . '/.' . $vendor . '.bridged';

			if (!is_dir($target)) {
				continue; // not installed, nothing to bridge
			}

			$fingerprint = $this->bridgeFingerprint($vendor);
			if ($fingerprint !== '' && is_dir($link) && @file_get_contents($marker) === $fingerprint) {
				continue; // already bridged at this exact version
			}

			$this->unbridge($link);

			$linked = @symlink($target, $link);
			if (!$linked) {
				$linked = $this->makeJunction($target, $link);
			}
			if (!$linked) {
				$this->copyRecursive($target, $link);
			}

			@file_put_contents($marker, $fingerprint);
		}

		return true;
	}

	/**
	 * Hash of the installed versions under a vendor namespace, so the bridge
	 * is only rebuilt when composer actually moves one of them.
	 *
	 * @param string $vendor Composer vendor namespace
	 * @return string
	 */
	private function bridgeFingerprint($vendor)
	{
		$installedJson = $this->paths->getModuleRoot() . '/vendor/composer/installed.json';
		if (!file_exists($installedJson)) {
			return '';
		}

		$data = json_decode(file_get_contents($installedJson), true);
		if (!is_array($data)) {
			return '';
		}
		$packages = isset($data['packages']) ? $data['packages'] : $data;

		$parts = array();
		foreach ($packages as $pkg) {
			if (!empty($pkg['name']) && strpos($pkg['name'], $vendor . '/') === 0) {
				$parts[] = $pkg['name'] . '@' . (isset($pkg['version']) ? $pkg['version'] : '?');
			}
		}
		if (count($parts) === 0) {
			return '';
		}
		sort($parts);

		return md5(implode(',', $parts));
	}

	/**
	 * Remove an existing bridge entry.
	 *
	 * rmdir() is tried before deleteRecursive() because a Windows junction
	 * looks like a directory to is_dir() and PHP does not reliably report it
	 * via is_link(); rmdir() removes the junction and leaves its target
	 * alone, while deleteRecursive() would follow it and delete the real
	 * Bootstrap files.
	 *
	 * @param string $link
	 * @return void
	 */
	private function unbridge($link)
	{
		if (is_link($link)) {
			if (!@unlink($link)) {
				@rmdir($link);
			}
			return;
		}

		if (is_dir($link)) {
			if (!@rmdir($link)) {
				$this->deleteRecursive($link);
			}
		}
	}

	/**
	 * Windows directory junction, which unlike a symlink needs no elevation.
	 *
	 * @param string $target
	 * @param string $link
	 * @return bool
	 */
	private function makeJunction($target, $link)
	{
		if (DIRECTORY_SEPARATOR !== '\\' || !function_exists('exec')) {
			return false;
		}

		$cmd = 'mklink /J ' . escapeshellarg(str_replace('/', '\\', $link)) .
			' ' . escapeshellarg(str_replace('/', '\\', $target));

		$output = array();
		$code = 1;
		@exec('cmd /c ' . $cmd . ' 2>&1', $output, $code);

		return $code === 0 && is_dir($link);
	}

	/**
	 * Recursively copy a directory (Cypht's site/ output isn't huge, this
	 * is only run when the button is clicked, not on every page load). Also
	 * used by CyphtPipeline::publishSite().
	 *
	 * @param string $src
	 * @param string $dst
	 * @return void
	 */
	public function copyRecursive($src, $dst)
	{
		if (!is_dir($dst)) {
			mkdir($dst, 0755, true);
		}
		$items = scandir($src);
		foreach ($items as $item) {
			if ($item === '.' || $item === '..') {
				continue;
			}
			$srcPath = $src . '/' . $item;
			$dstPath = $dst . '/' . $item;
			if (is_dir($srcPath)) {
				$this->copyRecursive($srcPath, $dstPath);
			} else {
				copy($srcPath, $dstPath);
			}
		}
	}

	/**
	 * Also used by CyphtPipeline::publishSite() to wipe the previous
	 * published copy before publishing a fresh one.
	 *
	 * @param string $dir
	 * @return void
	 */
	public function deleteRecursive($dir)
	{
		$items = scandir($dir);
		foreach ($items as $item) {
			if ($item === '.' || $item === '..') {
				continue;
			}
			$path = $dir . '/' . $item;
			if (is_dir($path)) {
				$this->deleteRecursive($path);
			} else {
				unlink($path);
			}
		}
		rmdir($dir);
	}
}
