-- Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see https://www.gnu.org/licenses/.
--
-- Migration 002: record which Cypht version wrote each stored user config.
--
-- The config column is a JSON blob whose shape belongs to Cypht. Without
-- this there is no way to tell which rows predate a format change.
-- The column is nullable because we don't want to break existing rows

ALTER TABLE llx_cyphtwebmail_userconfig ADD COLUMN cypht_version varchar(32) NULL;
